require_relative "Pieces/king"
require_relative "Pieces/queen"
require_relative "Pieces/bishop"
require_relative "Pieces/knight"
require_relative "Pieces/rook"
require_relative "Pieces/pawn"
require_relative "Pieces/empty_square" 
